### PR TITLE
fix _isa_version for non-ref vobj

### PR DESCRIPTION
**Pull request by rurban**

### CODE REVIEW

**Comment by karenetheridge** [comment]
is there a test we can add to demonstrate this fix?

**Comment by rurban** [comment]
Only with my private version extensions

**Comment by dagolden** [comment]
@rurban -- could you please explain what a "non-ref" object is and how one is generated?

**Comment by rurban** [comment]
I said non-ref vobj, not obj. 
If the $vobj being passed to _isa_version is a string or number, as it happens here:

```
  if (not defined $version or (!ref($version) && $version eq '0')) {
    return $V0;
  }
  elsif ( ref($version) eq 'version' || _isa_version($version) ) {
    $vobj = $version;
  }
```

A normal version object (isa 'version') is covered before. 
A non-ref $vobj is also covered, but only if it's eq '0'. 
So any non-'0' string or number will be passed to _isa_version() and will fail there.

How generated? The API of e.g.  accepts_module and exact_version accept 
a version number or version string, which will fail.

**Comment by dagolden** [comment]
I'm still not sure what kind of version extensions you have that fail this, but I can replicate it with a version of "version" (class 'version' isa 'version').  I fixed it by checking for `ref` before calling the function for a minor optimization.

@rurban thanks for finding that obscure bug!

**Pull request closed without merging**
